投票网页django/files/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

投票网页django/files/mysite/polls/urls.py
from django.conf.urls import url

from .views import index, detail, results, vote

app_name = 'polls'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^([0-9]+)/$', detail, name='detail'),
    url(r'^([0-9]+)/results/$', results, name='results'),
    url(r'^([0-9]+)/vote/$', vote, name='vote'),
]

投票网页django/files/mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=128)
    pub_date = models.DateTimeField()

    def __str__(self):
        return fmt_text(self.question_text)

    def __repr__(self):
        return self.__str__()


class Choice(models.Model):
    choice_text = models.CharField(max_length=128)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey('Question')

    def __str__(self):
        return fmt_text(self.choice_text)

    def __repr__(self):
        return self.__str__()


def fmt_text(text):
    if len(text) <= 50:
        return text
    else:
        return text[:50] + '...'

投票网页django/files/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice


def index(request):
    # 显示最新的5条问题
    questions = Question.objects.all().order_by('-pub_date')[:5]
    return render(request, "polls/index.html", {'questions': questions})


def detail(request, pk):
    q = get_object_or_404(Question, pk=pk)
    return render(request, "polls/detail.html", {'q': q})


def results(request, pk):
    q = get_object_or_404(Question, pk=pk)
    return render(request, "polls/results.html", {'q': q})


def vote(request, pk):
    """ 更新用户所选择的选项的投票总数 """
    q = get_object_or_404(Question, pk=pk)
    choice_pk = request.POST.get('choice')
    if not choice_pk or not choice_pk.isdigit():
        # 没有有效的choice_pk，出错
        error = "Please select a choice"
        return render(request, "polls/detail.html", {'q': q, 'error': error})
    choice_pk = int(choice_pk)
    choice = get_object_or_404(Choice, pk=choice_pk)
    choice.votes += 1
    choice.save()
    next_url = reverse('polls:results', args=(pk,))
    return HttpResponseRedirect(next_url)

投票网页django/files/mysite/polls/templates/polls/detail.html
<html>
<head>
<meta charset="utf-8">
<title>Detail: {{ q.question_text }}</title>
</head>
<body>

<p>{{ q.question_text }}</p>
{% if error %}
<p>{{ error }}</p>
{% endif %}
<form method="post" action="{% url "polls:vote" q.pk %}">
{% csrf_token %}
{% for c in q.choice_set.all %}
<input type="radio" name="choice" id="choice{{ c.pk }}" value={{ c.pk }}><label for="choice{{ c.pk }}">{{ c.choice_text }}</label><br>
{% endfor %}
<br>
<input type="submit" value="OK">
</form>

</body>
</html>

投票网页django/files/mysite/polls/templates/polls/index.html
<html>
<head>
<meta charset="utf-8">
<title>Qustion List</title>
</head>
<body>
<ul>
{% for q in questions %}
  <li><a href="{% url "polls:detail" q.pk %}">{{ q.question_text }}</a></li>
{% endfor %}
</ul>
</body>
</html>

投票网页django/files/mysite/polls/templates/polls/results.html
<html>
<head>
<meta charset="utf-8">
<title>Results: {{ q.question_text }}</title>
</head>
<body>

<p>{{ q.question_text }}</p>
<ul>
{% for c in q.choice_set.all %}
  <li>{{ c.choice_text }} -- {{ c.votes }} vote{{ c.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url "polls:detail" q.pk %}">Vote again?</a>

</body>
</html>